functionsDirectory = "C:\\Users\\abdur rahman\\Desktop\\social-hub\\netlify\\functions"
functionsDirectoryOrigin = "default"
headers = []
redirects = []

[build]
publish = "C:\\Users\\abdur rahman\\Desktop\\social-hub\\.next"
publishOrigin = "config"
commandOrigin = "config"
base = "C:\\Users\\abdur rahman\\Desktop\\social-hub"
command = "npm run build"
functions = "C:\\Users\\abdur rahman\\Desktop\\social-hub\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[env]
NEXT_PRIVATE_TARGET = "server"

[functions]

[functions."*"]

[[plugins]]
origin = "config"
package = "@netlify/plugin-nextjs"

[plugins.inputs]